// Precomputes every basic-strategy chart and the expected-return table from the
// probability engine and writes src/engine/charts-data.js.
//   npm run build:charts
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { buildChart, expectedReturns, HARD_ROWS, SOFT_ROWS, PAIR_ROWS } from '../src/engine/chart-builder.js';
import { DECK_OPTIONS, chartKey } from '../src/engine/rules.js';

const outFile = fileURLToPath(new URL('../src/engine/charts-data.js', import.meta.url));
const charts = {};
const returns = {};
const started = Date.now();

for (const decks of DECK_OPTIONS) {
  for (const dealerHitsSoft17 of [false, true]) {
    for (const doubleAfterSplit of [true, false]) {
      const key = chartKey({ decks, dealerHitsSoft17, doubleAfterSplit });
      const t0 = Date.now();
      const built = buildChart({ decks, dealerHitsSoft17, doubleAfterSplit });
      const er = expectedReturns(built);
      charts[key] = built.chart;
      returns[key] = {
        naturalPaid: Number(er.naturalPaid.toFixed(6)),
        returns: Object.fromEntries(Object.entries(er.returns).map(([k, v]) => [k, Number(v.toFixed(6))])),
      };
      console.log(`${key.padEnd(14)} ${((Date.now() - t0) / 1000).toFixed(1)}s  edge ${(-er.returns['none|any|4|0'] * 100).toFixed(3)}% (no surrender)`);
    }
  }
}

function rows(table, keys) {
  return keys.map((k) => `      ${k}: '${table[k].join(' ')}',`).join('\n');
}

const body = Object.entries(charts)
  .map(([key, c]) => `  '${key}': {\n    hard: {\n${rows(c.hard, HARD_ROWS)}\n    },\n    soft: {\n${rows(c.soft, SOFT_ROWS)}\n    },\n    pairs: {\n${rows(c.pairs, PAIR_ROWS)}\n    },\n  },`)
  .join('\n');

const text = `// Generated by scripts/build-charts.mjs from the probability engine. Do not edit by hand.
//
// CHARTS[key].hard[total], .soft[total] and .pairs[value] hold 10 space-separated
// cells for dealer up cards 2,3,4,5,6,7,8,9,10,A. Each cell lists the actions from best
// to worst by expected value (H hit, S stand, D double, R surrender, P split),
// averaged over the two-card hands that make that cell. The recommendation is the
// first action that the rules and the current hand allow.
//
// EXPECTED_RETURNS[key].returns['<surrender>|<doubleOn>|<maxSplitHands>|<resplitAces>']
// is the long-run expected return per unit staked (negative = house edge) at 3:2;
// naturalPaid converts it to other blackjack payouts.

export const CHARTS = {
${body}
};

export const EXPECTED_RETURNS = {
${Object.entries(returns).map(([k, v]) => `  '${k}': ${JSON.stringify(v)},`).join('\n')}
};
`;

writeFileSync(outFile, text);
console.log(`Wrote ${outFile} in ${((Date.now() - started) / 1000).toFixed(1)}s`);
